const state = { rows: [], columns: [], filters: {}, chart: null, fileName: '', excelWorkbook: null, excelFileName: '', originalRows: [], originalColumns: [], history: [], dictionary: {}, branding: { title: 'Dashboard intelligence', organization: 'SIWES Data Science Project', theme: 'dark', accent: '#9b8cff' } };
const $ = id => document.getElementById(id);
const empty = v => v === undefined || v === null || String(v).trim() === '';
const number = v => { const n = Number(String(v).replace(/,/g, '')); return Number.isFinite(n) ? n : null; };
const format = n => new Intl.NumberFormat(undefined,{maximumFractionDigits:2}).format(n);

function parseCSV(text) {
  const rows = []; let row = [], cell = '', quoted = false;
  for (let i = 0; i < text.length; i++) { const c = text[i], next = text[i + 1];
    if (c === '"' && quoted && next === '"') { cell += '"'; i++; }
    else if (c === '"') quoted = !quoted;
    else if (c === ',' && !quoted) { row.push(cell.trim()); cell = ''; }
    else if ((c === '\n' || c === '\r') && !quoted) { if (c === '\r' && next === '\n') i++; row.push(cell.trim()); if (row.some(x => x !== '')) rows.push(row); row = []; cell = ''; }
    else cell += c;
  }
  row.push(cell.trim()); if (row.some(x => x !== '')) rows.push(row);
  return rows;
}
function infer(values) { const existing = values.filter(v => !empty(v)); if (!existing.length) return 'Empty'; return existing.every(v => number(v) !== null) ? 'Number' : 'Text'; }
function numericValues(col) { return state.rows.map(r => number(r[col])).filter(v => v !== null); }
function filteredRows() { return state.rows.filter(r => Object.entries(state.filters).every(([c, value]) => !value || String(r[c]).toLowerCase().includes(value.toLowerCase()))); }
function render() {
  const cells = state.rows.length * state.columns.length;
  const missing = state.rows.reduce((sum,r) => sum + state.columns.filter(c => empty(r[c])).length, 0);
  $('recordCount').textContent = format(state.rows.length); $('columnCount').textContent = format(state.columns.length);
  $('missingCount').textContent = format(missing); $('missingRate').textContent = `${cells ? ((missing / cells) * 100).toFixed(1) : 0}% of all cells`;
  $('completeness').textContent = `${cells ? (100 - missing / cells * 100).toFixed(1) : 0}%`;
  $('qualityBody').innerHTML = state.columns.map(c => { const m = state.rows.filter(r => empty(r[c])).length, good = state.rows.length ? 100 - m / state.rows.length * 100 : 0; return `<tr><td>${escapeHTML(c)}</td><td><span class="type-pill">${infer(state.rows.map(r=>r[c]))}</span></td><td class="right">${format(m)} <span class="subtle">(${state.rows.length ? (m/state.rows.length*100).toFixed(1):0}%)</span></td><td><span class="progress"><i style="width:${good}%"></i></span><span class="subtle">${good.toFixed(1)}%</span></td></tr>`; }).join('');
  const numeric = state.columns.filter(c => infer(state.rows.map(r => r[c])) === 'Number');
  $('statsBody').innerHTML = numeric.length ? numeric.map(c => { const v=numericValues(c), avg=v.reduce((a,b)=>a+b,0)/v.length; return `<tr><td>${escapeHTML(c)}</td><td class="right">${format(avg)}</td><td class="right">${format(Math.min(...v))}</td><td class="right">${format(Math.max(...v))}</td></tr>`; }).join('') : '<tr><td colspan="4" class="empty">No numeric columns were detected.</td></tr>';
  setupChartOptions(numeric); renderValidation(); renderCorrelation(numeric); renderInsights(numeric); renderCleaningControls(numeric); renderDictionary(); renderFilters(); renderPreview();
}
function setupChartOptions(numeric) {
  const category = $('categoryColumn'), value = $('valueColumn'); const oldC=category.value, oldV=value.value;
  category.innerHTML = state.columns.map(c=>`<option value="${escapeAttr(c)}">${escapeHTML(c)}</option>`).join('');
  value.innerHTML = numeric.map(c=>`<option value="${escapeAttr(c)}">${escapeHTML(c)}</option>`).join('') || '<option value="">Count of records</option>';
  category.value = state.columns.includes(oldC) ? oldC : state.columns[0]; value.value = numeric.includes(oldV) ? oldV : (numeric[0] || ''); renderChart();
}
function renderChart() {
  if (!state.rows.length || !window.Chart) return;
  const c=$('categoryColumn').value,v=$('valueColumn').value,type=$('chartType').value,aggregation=$('aggregation').value,rows=filteredRows();
  const aggregate=values=>{const nums=values.filter(x=>x!==null);if(aggregation==='count')return values.length;if(!nums.length)return 0;if(aggregation==='sum')return nums.reduce((a,b)=>a+b,0);if(aggregation==='average')return nums.reduce((a,b)=>a+b,0)/nums.length;if(aggregation==='min')return Math.min(...nums);return Math.max(...nums);};
  let config, hint='';
  if(type==='scatter'){
    const points=rows.map(r=>({x:number(r[c]),y:number(r[v])})).filter(p=>p.x!==null&&p.y!==null).slice(0,500);
    hint='Scatter plots need two numeric columns: X axis and Y axis.';
    config={type:'scatter',data:{datasets:[{label:`${v} by ${c}`,data:points,backgroundColor:'#4ce2c1',pointRadius:5,pointHoverRadius:7}]},options:{...chartOptions(false),scales:{x:{title:{display:true,text:c,color:'#9399ab'},ticks:{color:'#9399ab'},grid:{color:'#292d3a'}},y:{title:{display:true,text:v,color:'#9399ab'},ticks:{color:'#9399ab'},grid:{color:'#292d3a'}}}}};
  } else if(type==='histogram') {
    const values=rows.map(r=>number(r[v])).filter(x=>x!==null),min=Math.min(...values),max=Math.max(...values),bins=8,width=(max-min||1)/bins,counts=Array(bins).fill(0); values.forEach(x=>counts[Math.min(bins-1,Math.floor((x-min)/width))]++); const labels=counts.map((_,i)=>`${format(min+i*width)}–${format(min+(i+1)*width)}`);
    hint='A histogram shows how frequently values occur across ranges.';
    config={type:'bar',data:{labels,datasets:[{label:`Frequency of ${v}`,data:counts,backgroundColor:'#9b8cff',borderRadius:4,borderWidth:0}]},options:chartOptions(false)};
  } else {
    const groups={};rows.forEach(r=>{const k=empty(r[c])?'(blank)':r[c];(groups[k]??=[]).push(number(r[v]));}); const entries=Object.entries(groups).map(([label,values])=>[label,aggregate(values)]).sort((a,b)=>b[1]-a[1]).slice(0,12);
    hint=`Showing ${aggregation} of ${v||'records'} grouped by ${c}.`;
    config={type,data:{labels:entries.map(x=>x[0]),datasets:[{label:`${aggregation} of ${v||'records'}`,data:entries.map(x=>x[1]),backgroundColor:type==='doughnut'?['#9b8cff','#4ce2c1','#ffbc5f','#ff6d85','#6ba8ff','#c58cff','#83d87a']:'#9b8cff',borderColor:'#4ce2c1',borderWidth:type==='line'?2:0,borderRadius:type==='bar'?5:0,fill:false,tension:.3}]},options:chartOptions(type==='doughnut')};
  }
  $('chartHint').textContent=hint;if(state.chart)state.chart.destroy();state.chart=new Chart($('mainChart'),config);
}
function chartOptions(isDonut){return {responsive:true,maintainAspectRatio:false,plugins:{legend:{display:isDonut,labels:{color:'#c9cede'}},tooltip:{callbacks:{label:ctx=>`${ctx.dataset.label}: ${format(ctx.raw?.y??ctx.raw)}`}}},scales:isDonut?{}:{x:{ticks:{color:'#9399ab'},grid:{display:false}},y:{ticks:{color:'#9399ab'},grid:{color:'#292d3a'},beginAtZero:true}}};}
function pearson(a,b) { const pairs=state.rows.map(r=>[number(r[a]),number(r[b])]).filter(x=>x[0]!==null&&x[1]!==null); if(pairs.length<2)return null; const ax=pairs.reduce((s,x)=>s+x[0],0)/pairs.length,by=pairs.reduce((s,x)=>s+x[1],0)/pairs.length; const top=pairs.reduce((s,[x,y])=>s+(x-ax)*(y-by),0), bottom=Math.sqrt(pairs.reduce((s,[x])=>s+(x-ax)**2,0)*pairs.reduce((s,[,y])=>s+(y-by)**2,0));return bottom?top/bottom:null; }
function renderValidation(){const alerts=[];const normalized=state.columns.map(c=>String(c).trim().toLowerCase()),duplicates=[...new Set(normalized.filter((c,i)=>normalized.indexOf(c)!==i))];if(duplicates.length)alerts.push({type:'error',text:`Duplicate column names found: ${duplicates.join(', ')}. Rename them so every field is distinct.`});const blankNames=state.columns.filter(c=>!String(c).trim()||/^Column \d+$/.test(c)===false&&String(c).trim()==='');if(blankNames.length)alerts.push({type:'error',text:`${format(blankNames.length)} column header${blankNames.length===1?' is':'s are'} empty.`});state.columns.forEach(c=>{const values=state.rows.map(r=>r[c]).filter(v=>!empty(v)),numeric=values.filter(v=>number(v)!==null).length,text=values.length-numeric;if(values.length>=5&&numeric>0&&text>0&&numeric/values.length>=.6)alerts.push({type:'warning',text:`${c} looks mostly numeric, but ${format(text)} value${text===1?' is':'s are'} text. Check for entries such as spaces, words, or invalid numbers.`});});const rowLengths=state.rows.filter(r=>Object.values(r).length!==state.columns.length).length;if(rowLengths)alerts.push({type:'warning',text:`${format(rowLengths)} row${rowLengths===1?' has':'s have'} a different number of fields than the header.`});if(state.rows.length>10000)alerts.push({type:'warning',text:`This dataset has ${format(state.rows.length)} records. Large files may be slower to analyse in a browser.`});if(!alerts.length)alerts.push({type:'ok',text:'No structural validation problems were detected. You can continue with cleaning and analysis.'});$('validationList').innerHTML=alerts.slice(0,8).map(a=>`<div class="validation-item ${a.type}"><span class="validation-icon" aria-hidden="true">${a.type==='ok'?'✓':a.type==='error'?'!':'▲'}</span><span>${escapeHTML(a.text)}</span></div>`).join('');}
function renderInsights(numeric){const findings=[],totalCells=state.rows.length*state.columns.length;const missing=state.columns.map(c=>({column:c,count:state.rows.filter(r=>empty(r[c])).length})).sort((a,b)=>b.count-a.count);if(missing[0]?.count){const top=missing[0];findings.push({type:'alert',text:`${top.column} has the most missing values: ${format(top.count)} of ${format(state.rows.length)} records (${(top.count/state.rows.length*100).toFixed(1)}%).`});}else findings.push({type:'positive',text:`Excellent data quality: all ${format(totalCells)} cells have values.`});const complete=missing.filter(x=>x.count===0);if(complete.length)findings.push({type:'positive',text:`${complete.slice(0,3).map(x=>x.column).join(', ')} ${complete.length===1?'has':'have'} no missing values.`});const relationships=[];numeric.forEach((a,i)=>numeric.slice(i+1).forEach(b=>{const correlation=pearson(a,b);if(correlation!==null)relationships.push({a,b,correlation});}));relationships.sort((a,b)=>Math.abs(b.correlation)-Math.abs(a.correlation));if(relationships.length){const r=relationships[0],word=r.correlation>=0?'positive':'negative';findings.push({type:'',text:`${r.a} and ${r.b} have the strongest ${word} relationship (correlation ${r.correlation.toFixed(2)}).`});}if(numeric.length){const summaries=numeric.map(c=>{const values=numericValues(c);return {column:c,average:values.reduce((a,b)=>a+b,0)/values.length};}).sort((a,b)=>b.average-a.average);if(summaries.length>1)findings.push({type:'',text:`${summaries[0].column} has the highest average value (${format(summaries[0].average)}) among numeric fields.`});}const categorical=state.columns.filter(c=>infer(state.rows.map(r=>r[c]))==='Text');if(categorical.length){const c=categorical[0],counts={};state.rows.forEach(r=>{const value=empty(r[c])?'(blank)':r[c];counts[value]=(counts[value]||0)+1;});const [leader,count]=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]||[];if(leader)findings.push({type:'',text:`The most common ${c} is ${leader}, appearing in ${format(count)} records.`});}$('insightsList').innerHTML=findings.length?findings.slice(0,5).map(f=>`<div class="insight ${f.type}"><i aria-hidden="true"></i><span>${escapeHTML(f.text)}</span></div>`).join(''):'<p class="subtle">Upload more data to generate findings.</p>';}
function renderCorrelation(numeric) { if(numeric.length<2){$('correlationContent').innerHTML='<p class="empty">Add at least two numeric columns to see a correlation matrix.</p>';return;} $('correlationContent').innerHTML=`<table class="correlation-table"><thead><tr><th></th>${numeric.map(c=>`<th>${escapeHTML(c)}</th>`).join('')}</tr></thead><tbody>${numeric.map(a=>`<tr><th>${escapeHTML(a)}</th>${numeric.map(b=>{const v=pearson(a,b), alpha=v===null?0:Math.abs(v)*.8+.08, color=v>=0?`rgba(76,226,193,${alpha})`:`rgba(255,109,133,${alpha})`;return `<td style="background:${color};color:${Math.abs(v||0)>.55?'#080b10':'#e8e9f0'}">${v===null?'—':v.toFixed(2)}</td>`}).join('')}</tr>`).join('')}</tbody></table>`; }
function renderCleaningControls(){const select=$('cleanColumn'),old=select.value;select.innerHTML=state.columns.map(c=>`<option value="${escapeAttr(c)}">${escapeHTML(c)}</option>`).join('');if([...select.options].some(o=>o.value===old))select.value=old;}
function cloneRows(rows){return rows.map(row=>({...row}));}
function captureHistory(){state.history.push({rows:cloneRows(state.rows),columns:[...state.columns],filters:{...state.filters}});if(state.history.length>10)state.history.shift();}
function applyCleaning(message){state.filters={};render();saveDashboard();$('cleaningStatus').textContent=message;}
function removeDuplicates(){captureHistory();const seen=new Set(),before=state.rows.length;state.rows=state.rows.filter(row=>{const key=state.columns.map(c=>row[c]).join('\u001f');if(seen.has(key))return false;seen.add(key);return true;});applyCleaning(`${format(before-state.rows.length)} duplicate rows removed.`);}
function removeMissingRows(){captureHistory();const before=state.rows.length;state.rows=state.rows.filter(row=>state.columns.every(c=>!empty(row[c])));applyCleaning(`${format(before-state.rows.length)} rows with missing values removed.`);}
function fillMissing(method){const column=$('cleanColumn').value,values=numericValues(column);if(!values.length){$('cleaningStatus').textContent='This column has no numeric values to use.';return;}captureHistory();const value=method==='average'?values.reduce((a,b)=>a+b,0)/values.length:[...values].sort((a,b)=>a-b)[Math.floor(values.length/2)];let changed=0;state.rows.forEach(row=>{if(empty(row[column])){row[column]=Number(value.toFixed(4));changed++;}});applyCleaning(`${format(changed)} missing values filled with the ${method}.`);}
function renameColumn(){const old=$('cleanColumn').value,next=$('renameColumnName').value.trim();if(!next){$('cleaningStatus').textContent='Enter a new column name first.';return;}if(state.columns.includes(next)&&next!==old){$('cleaningStatus').textContent='That column name already exists.';return;}captureHistory();state.columns=state.columns.map(c=>c===old?next:c);state.rows.forEach(row=>{row[next]=row[old];delete row[old];});if(state.filters[old]!==undefined){state.filters[next]=state.filters[old];delete state.filters[old];}if(state.dictionary[old]){state.dictionary[next]=state.dictionary[old];delete state.dictionary[old];}$('renameColumnName').value='';applyCleaning(`Column renamed from ${old} to ${next}.`);}
function removeColumn(){const column=$('cleanColumn').value;if(state.columns.length<2){$('cleaningStatus').textContent='A dataset must keep at least one column.';return;}captureHistory();state.columns=state.columns.filter(c=>c!==column);state.rows.forEach(row=>delete row[column]);delete state.filters[column];delete state.dictionary[column];applyCleaning(`Column ${column} removed.`);}
function undoCleaning(){const previous=state.history.pop();if(!previous){$('cleaningStatus').textContent='There is no cleaning action to undo.';return;}state.rows=previous.rows;state.columns=previous.columns;state.filters=previous.filters;render();saveDashboard();$('cleaningStatus').textContent='Last cleaning action undone.';}
function resetCleaning(){if(!state.originalRows.length){$('cleaningStatus').textContent='No original dataset is available to restore.';return;}state.rows=cloneRows(state.originalRows);state.columns=[...state.originalColumns];state.filters={};state.history=[];render();saveDashboard();$('cleaningStatus').textContent='Dataset reset to its original uploaded version.';}
function renderDictionary(){const body=$('dictionaryBody');body.innerHTML=state.columns.map(c=>{const entry=state.dictionary[c]||{},example=state.rows.find(r=>!empty(r[c]))?.[c]??'—';return `<tr><td><strong>${escapeHTML(c)}</strong></td><td><span class="type-pill">${infer(state.rows.map(r=>r[c]))}</span></td><td><input data-dictionary="displayName" data-column="${escapeAttr(c)}" value="${escapeAttr(entry.displayName||'')}" placeholder="Friendly name"></td><td><input data-dictionary="description" data-column="${escapeAttr(c)}" value="${escapeAttr(entry.description||'')}" placeholder="What does it mean?"></td><td><input data-dictionary="unit" data-column="${escapeAttr(c)}" value="${escapeAttr(entry.unit||'')}" placeholder="e.g. Naira"></td><td>${escapeHTML(example)}</td></tr>`;}).join('');document.querySelectorAll('[data-dictionary]').forEach(input=>input.addEventListener('input',e=>{const col=e.target.dataset.column;state.dictionary[col]??={};state.dictionary[col][e.target.dataset.dictionary]=e.target.value;}));}
function saveDictionary(){saveDashboard();$('dictionaryStatus').textContent='Data dictionary saved with this dashboard on this device.';}
function applyBranding(){const b=state.branding;document.body.classList.toggle('light-theme',b.theme==='light'||(b.theme==='system'&&window.matchMedia('(prefers-color-scheme: light)').matches));document.documentElement.style.setProperty('--purple',b.accent);$('dashboardTitle').textContent=b.title||'Dashboard intelligence';$('organizationLabel').textContent=(b.organization||'SIWES Data Science Project').toUpperCase();$('brandingTitle').value=b.title||'';$('brandingOrganization').value=b.organization||'';$('themeSelector').value=b.theme||'dark';$('accentColor').value=b.accent||'#9b8cff';}
function saveBranding(){state.branding={title:$('brandingTitle').value.trim()||'Dashboard intelligence',organization:$('brandingOrganization').value.trim()||'SIWES Data Science Project',theme:$('themeSelector').value,accent:$('accentColor').value};applyBranding();saveDashboard();$('brandingStatus').textContent='Branding saved and applied to this dashboard.';}
function renderFilters(){ $('filterControls').innerHTML=state.columns.slice(0,5).map(c=>`<label>${escapeHTML(c)}<input data-filter="${escapeAttr(c)}" value="${escapeAttr(state.filters[c]||'')}" placeholder="Filter…"></label>`).join(''); document.querySelectorAll('[data-filter]').forEach(i=>i.addEventListener('input',e=>{state.filters[e.target.dataset.filter]=e.target.value;renderPreview();renderChart();saveDashboard();})); }
function renderPreview(){ const rows=filteredRows(); $('filterResult').textContent=`Showing ${format(rows.length)} of ${format(state.rows.length)} records`; $('previewHead').innerHTML=`<tr>${state.columns.map(c=>`<th>${escapeHTML(c)}</th>`).join('')}</tr>`; $('previewBody').innerHTML=rows.slice(0,100).map(r=>`<tr>${state.columns.map(c=>`<td>${empty(r[c])?'<span class="subtle">—</span>':escapeHTML(r[c])}</td>`).join('')}</tr>`).join('')||`<tr><td colspan="${state.columns.length}" class="empty">No records match these filters.</td></tr>`; }
function pdfTable(doc,options){doc.autoTable({theme:'grid',styles:{fontSize:8,cellPadding:5,textColor:[33,38,50],lineColor:[220,223,230]},headStyles:{fillColor:[50,45,90],textColor:[255,255,255],fontStyle:'bold'},margin:{left:40,right:40},...options});return doc.lastAutoTable.finalY;}
function exportPdfReport(){if(!window.jspdf){alert('The PDF generator did not load. Please refresh and try again.');return;}const {jsPDF}=window.jspdf,doc=new jsPDF({unit:'pt',format:'a4'});if(typeof doc.autoTable!=='function'){alert('The PDF table generator did not load. Please refresh and try again.');return;}const pageWidth=doc.internal.pageSize.getWidth(),now=new Date(),numeric=state.columns.filter(c=>infer(state.rows.map(r=>r[c]))==='Number'),missing=state.rows.reduce((sum,r)=>sum+state.columns.filter(c=>empty(r[c])).length,0),cells=state.rows.length*state.columns.length,activeFilters=Object.entries(state.filters).filter(([,v])=>v).map(([c,v])=>`${c}: ${v}`).join(' | ')||'None';doc.setFillColor(17,20,29);doc.rect(0,0,pageWidth,92,'F');doc.setTextColor(245,246,250);doc.setFontSize(20);doc.text('SIWES Data Science Project Dashboard',40,42);doc.setFontSize(10);doc.setTextColor(190,194,210);doc.text(`Analysis report - ${now.toLocaleString()}`,40,64);doc.setTextColor(35,40,52);doc.setFontSize(14);doc.text(state.fileName||'Dataset',40,122);doc.setFontSize(9);doc.setTextColor(90,96,110);doc.text(`Active filters: ${activeFilters}`,40,140,{maxWidth:515});let y=164;doc.setTextColor(35,40,52);doc.setFontSize(12);doc.text('Dataset summary',40,y);y=pdfTable(doc,{startY:y+10,head:[['Records','Columns','Missing cells','Completeness']],body:[[format(state.rows.length),format(state.columns.length),format(missing),`${cells?(100-missing/cells*100).toFixed(1):0}%`]]});doc.setFontSize(12);doc.text('Data quality',40,y+25);y=pdfTable(doc,{startY:y+35,head:[['Column','Type','Missing','Completeness']],body:state.columns.slice(0,40).map(c=>{const m=state.rows.filter(r=>empty(r[c])).length;return[c,infer(state.rows.map(r=>r[c])),`${format(m)} (${state.rows.length?(m/state.rows.length*100).toFixed(1):0}%)`,`${state.rows.length?(100-m/state.rows.length*100).toFixed(1):0}%`];})});if(numeric.length){doc.addPage();y=52;doc.setTextColor(35,40,52);doc.setFontSize(12);doc.text('Numeric summary statistics',40,y);y=pdfTable(doc,{startY:y+10,head:[['Column','Average','Minimum','Maximum']],body:numeric.slice(0,40).map(c=>{const values=numericValues(c),avg=values.reduce((a,b)=>a+b,0)/values.length;return[c,format(avg),format(Math.min(...values)),format(Math.max(...values))];})});const pairs=[];numeric.forEach((a,i)=>numeric.slice(i+1).forEach(b=>{const value=pearson(a,b);if(value!==null)pairs.push([a,b,value]);}));if(pairs.length){doc.setFontSize(12);doc.text('Strongest numeric relationships',40,y+25);y=pdfTable(doc,{startY:y+35,head:[['Column A','Column B','Correlation']],body:pairs.sort((a,b)=>Math.abs(b[2])-Math.abs(a[2])).slice(0,10).map(([a,b,v])=>[a,b,v.toFixed(2)])});}}
  if(state.chart){doc.addPage();doc.setTextColor(35,40,52);doc.setFontSize(12);doc.text('Current chart',40,52);const chartImage=$('mainChart').toDataURL('image/png',1);const props=doc.getImageProperties(chartImage),width=515,height=Math.min(330,props.height*width/props.width);doc.addImage(chartImage,'PNG',40,70,width,height);doc.setFontSize(9);doc.setTextColor(90,96,110);doc.text($('chartHint').textContent,40,88+height,{maxWidth:515});}
  const pages=doc.getNumberOfPages();for(let p=1;p<=pages;p++){doc.setPage(p);doc.setFontSize(8);doc.setTextColor(110,115,128);doc.text(`SIWES Data Science Project Dashboard - Page ${p} of ${pages}`,40,820);}doc.save(`siwes-dashboard-report-${now.toISOString().slice(0,10)}.pdf`);}
function escapeHTML(v){return String(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));} function escapeAttr(v){return escapeHTML(v);}
$('aggregation').addEventListener('change',renderChart);
$('removeDuplicates').addEventListener('click',removeDuplicates);
$('removeMissingRows').addEventListener('click',removeMissingRows);
$('fillAverage').addEventListener('click',()=>fillMissing('average'));
$('fillMedian').addEventListener('click',()=>fillMissing('median'));
$('renameColumn').addEventListener('click',renameColumn);
$('removeColumn').addEventListener('click',removeColumn);
$('undoCleaning').addEventListener('click',undoCleaning);
$('resetCleaning').addEventListener('click',resetCleaning);
$('saveDictionary').addEventListener('click',saveDictionary);
$('saveBranding').addEventListener('click',saveBranding);
$('saveSnapshot').addEventListener('click',saveSnapshot);
$('snapshotName').addEventListener('keydown',e=>{if(e.key==='Enter')saveSnapshot();});
$('refreshInsights').addEventListener('click',()=>renderInsights(state.columns.filter(c=>infer(state.rows.map(r=>r[c]))==='Number')));
$('pdfReportButton').addEventListener('click',exportPdfReport);
$('uploadState').addEventListener('drop',e=>{e.preventDefault();e.stopImmediatePropagation();$('uploadState').classList.remove('drag-active');const file=[...e.dataTransfer.files].find(f=>/\.(csv|xlsx|xls)$/i.test(f.name));if(file)loadFile(file);else alert('Please drop a CSV, XLSX, or XLS file.');},true);
function dashboardSettings(){return {chartType:$('chartType').value,categoryColumn:$('categoryColumn').value,valueColumn:$('valueColumn').value,aggregation:$('aggregation').value};}
function dashboardPayload(){return {columns:state.columns,rows:state.rows,fileName:state.fileName,filters:state.filters,settings:dashboardSettings(),originalColumns:state.originalColumns,originalRows:state.originalRows,dictionary:state.dictionary,branding:state.branding};}
function getSnapshots(){try{return JSON.parse(localStorage.getItem('siwes-snapshots-v1'))||[];}catch{return [];}}
function renderSnapshots(){const snapshots=getSnapshots();$('snapshotList').innerHTML=snapshots.length?snapshots.map(s=>`<div class="snapshot-item"><div class="snapshot-meta"><strong>${escapeHTML(s.name)}</strong><span>${escapeHTML(s.fileName||'Dataset')} - ${format(s.rows?.length||0)} rows - ${new Date(s.savedAt).toLocaleString()}</span></div><div class="snapshot-actions"><button class="button secondary" data-load-snapshot="${escapeAttr(s.id)}" type="button">Restore</button><button class="button danger-button" data-delete-snapshot="${escapeAttr(s.id)}" type="button">Delete</button></div></div>`).join(''):'<p class="subtle">No saved snapshots yet.</p>';document.querySelectorAll('[data-load-snapshot]').forEach(b=>b.addEventListener('click',()=>loadSnapshot(b.dataset.loadSnapshot)));document.querySelectorAll('[data-delete-snapshot]').forEach(b=>b.addEventListener('click',()=>deleteSnapshot(b.dataset.deleteSnapshot)));}
function saveSnapshot(){const name=$('snapshotName').value.trim();if(!name){$('snapshotStatus').textContent='Give this snapshot a name first.';return;}try{const snapshots=getSnapshots();snapshots.unshift({id:`s${Date.now()}`,name,savedAt:new Date().toISOString(),...dashboardPayload()});localStorage.setItem('siwes-snapshots-v1',JSON.stringify(snapshots.slice(0,12)));$('snapshotName').value='';renderSnapshots();$('snapshotStatus').textContent=`Snapshot “${name}” saved.`;}catch{$('snapshotStatus').textContent='This dataset is too large to save as another snapshot in this browser.';}}
function loadSnapshot(id){const snapshot=getSnapshots().find(s=>s.id===id);if(!snapshot)return;state.columns=snapshot.columns;state.rows=snapshot.rows;state.originalColumns=snapshot.originalColumns||[...snapshot.columns];state.originalRows=snapshot.originalRows||cloneRows(snapshot.rows);state.filters=snapshot.filters||{};state.dictionary=snapshot.dictionary||{};state.branding={...state.branding,...(snapshot.branding||{})};state.history=[];state.fileName=snapshot.fileName||snapshot.name;$('uploadState').hidden=true;$('dashboard').hidden=false;$('datasetName').textContent=state.fileName;$('loadInfo').textContent=`${format(state.rows.length)} rows - restored snapshot`;applyBranding();render();applySettings(snapshot.settings);saveDashboard();$('snapshotStatus').textContent=`Snapshot “${snapshot.name}” restored.`;}
function deleteSnapshot(id){const snapshot=getSnapshots().find(s=>s.id===id),remaining=getSnapshots().filter(s=>s.id!==id);localStorage.setItem('siwes-snapshots-v1',JSON.stringify(remaining));renderSnapshots();$('snapshotStatus').textContent=snapshot?`Snapshot “${snapshot.name}” deleted.`:'Snapshot deleted.';}
function saveDashboard(){if(!state.rows.length)return;try{localStorage.setItem('siwes-dashboard-v1',JSON.stringify({columns:state.columns,rows:state.rows,fileName:state.fileName,filters:state.filters,settings:dashboardSettings(),originalColumns:state.originalColumns,originalRows:state.originalRows,dictionary:state.dictionary,branding:state.branding}));$('saveStatus').textContent='Latest dashboard saved on this device';}catch(error){$('saveStatus').textContent='Dataset is too large to save in this browser';}}
function applySettings(settings={}){for(const [id,value] of Object.entries(settings)){const control=$(id);if(control&&[...control.options].some(o=>o.value===value))control.value=value;}renderChart();}
function setDataset(raw,fileName,source='loaded locally') { if(raw.length<2){alert('Please choose a file with a header row and at least one data row.');return;}state.columns=raw[0].map((c,i)=>String(c||`Column ${i+1}`));state.rows=raw.slice(1).map(r=>Object.fromEntries(state.columns.map((c,i)=>[c,r[i]??''])));state.originalColumns=[...state.columns];state.originalRows=cloneRows(state.rows);state.history=[];state.dictionary={};state.fileName=fileName;state.filters={};$('uploadState').hidden=true;$('dashboard').hidden=false;$('datasetName').textContent=fileName;$('loadInfo').textContent=`${format(state.rows.length)} rows · ${source}`;render();saveDashboard(); }
function restoreSavedDashboard(){try{const saved=JSON.parse(localStorage.getItem('siwes-dashboard-v1'));if(!saved?.rows?.length||!saved?.columns?.length){applyBranding();return;}state.columns=saved.columns;state.rows=saved.rows;state.originalColumns=saved.originalColumns||[...saved.columns];state.originalRows=saved.originalRows||cloneRows(saved.rows);state.history=[];state.dictionary=saved.dictionary||{};state.branding={...state.branding,...(saved.branding||{})};state.fileName=saved.fileName||'Saved dashboard';state.filters=saved.filters||{};$('uploadState').hidden=true;$('dashboard').hidden=false;$('datasetName').textContent=state.fileName;$('loadInfo').textContent=`${format(state.rows.length)} rows · restored from this browser`;applyBranding();render();applySettings(saved.settings);$('saveStatus').textContent='Latest dashboard restored from this device';}catch(error){localStorage.removeItem('siwes-dashboard-v1');applyBranding();}}
['chartType','categoryColumn','valueColumn','aggregation'].forEach(id=>$(id).addEventListener('change',saveDashboard));
$('clearSavedDashboard').addEventListener('click',()=>{localStorage.removeItem('siwes-dashboard-v1');state.rows=[];state.columns=[];state.originalRows=[];state.originalColumns=[];state.history=[];state.filters={};if(state.chart)state.chart.destroy();$('dashboard').hidden=true;$('uploadState').hidden=false;$('fileInput').value='';});
$('sampleButton').addEventListener('click',()=>setTimeout(saveDashboard,0));
$('sampleButton').addEventListener('click',()=>{state.excelWorkbook=null;state.excelFileName='';$('excelSheetControls').hidden=true;});
$('sheetSelector').addEventListener('change',e=>loadExcelSheet(e.target.value));
$('clearSavedDashboard').addEventListener('click',()=>{state.excelWorkbook=null;state.excelFileName='';$('excelSheetControls').hidden=true;});
restoreSavedDashboard();
renderSnapshots();
function loadExcelSheet(sheetName){if(!state.excelWorkbook)return;const raw=XLSX.utils.sheet_to_json(state.excelWorkbook.Sheets[sheetName],{header:1,defval:''});setDataset(raw,state.excelFileName,`Excel sheet: ${sheetName}`);}
function loadFile(file){const extension=file.name.split('.').pop().toLowerCase();if(extension==='csv'){state.excelWorkbook=null;state.excelFileName='';$('excelSheetControls').hidden=true;const reader=new FileReader();reader.onload=()=>setDataset(parseCSV(reader.result),file.name);reader.readAsText(file);return;}if(!['xlsx','xls'].includes(extension)){alert('Please choose a CSV, XLSX, or XLS file.');return;}if(!window.XLSX){alert('The Excel reader did not load. Please refresh and try again.');return;}file.arrayBuffer().then(buffer=>{state.excelWorkbook=XLSX.read(buffer);state.excelFileName=file.name;const selector=$('sheetSelector');selector.innerHTML=state.excelWorkbook.SheetNames.map(name=>`<option value="${escapeAttr(name)}">${escapeHTML(name)}</option>`).join('');$('excelSheetControls').hidden=false;selector.value=state.excelWorkbook.SheetNames[0];loadExcelSheet(selector.value);}).catch(()=>alert('This Excel file could not be read. Please try another file.'));}
function loadSample(){const raw=parseCSV(`Student ID,Department,Hours Studied,Attendance,Assessment Score,Project Score,Final Score\nSIWES-001,Data Science,18,92,78,88,83\nSIWES-002,Data Science,25,97,89,94,91\nSIWES-003,Computer Science,12,76,61,72,66\nSIWES-004,Data Science,22,90,83,91,87\nSIWES-005,Statistics,15,84,70,75,73\nSIWES-006,Computer Science,28,99,95,97,96\nSIWES-007,Statistics,10,68,55,,60\nSIWES-008,Data Science,20,93,81,86,84\nSIWES-009,Computer Science,16,82,67,79,72\nSIWES-010,Statistics,24,95,90,89,91`);state.columns=raw[0];state.rows=raw.slice(1).map(r=>Object.fromEntries(state.columns.map((c,i)=>[c,r[i]||''])));state.fileName='siwes-sample-data.csv';state.filters={};$('uploadState').hidden=true;$('dashboard').hidden=false;$('datasetName').textContent='SIWES sample data';$('loadInfo').textContent=`${format(state.rows.length)} rows · built-in sample`;render();}
const dropZone=$('uploadState');['dragenter','dragover'].forEach(event=>dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.add('drag-active');}));['dragleave','drop'].forEach(event=>dropZone.addEventListener(event,e=>{e.preventDefault();dropZone.classList.remove('drag-active');}));dropZone.addEventListener('drop',e=>{const file=[...e.dataTransfer.files].find(f=>f.name.toLowerCase().endsWith('.csv'));if(file)loadFile(file);else alert('Please drop a CSV file.');});$('sampleButton').addEventListener('click',loadSample);$('fileInput').addEventListener('change',e=>e.target.files[0]&&loadFile(e.target.files[0]));$('replaceFile').addEventListener('click',()=>$('fileInput').click());$('chartType').addEventListener('change',renderChart);$('categoryColumn').addEventListener('change',renderChart);$('valueColumn').addEventListener('change',renderChart);$('downloadButton').addEventListener('click',()=>{const data=[state.columns,...filteredRows().map(r=>state.columns.map(c=>`"${String(r[c]).replace(/"/g,'""')}"`))].map(r=>r.join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([data],{type:'text/csv'}));a.download='filtered-'+state.fileName;a.click();URL.revokeObjectURL(a.href);});
